site_name: NUH Data
site_url: https://health-informatics-uon.github.io/nuh-data/
repo_url: https://github.com/health-informatics-uon/nuh-data
docs_dir: docs

theme:
  name: material
  palette:
    scheme: default
    primary: teal

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
