# This workflow is used to release the project.
# It is triggered by a push to the main branch.
# And run semantic release

name: Release
permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: health-informatics-uon/workflows/.github/workflows/semantic-release.yml@1.4.7
    with:
      node-version: "24"
    secrets: inherit
